spring:
  datasource:
    driver: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/messenger_db
    username: postgres
    password: postgres

  liquibase:
    enabled: true
    change-log: classpath:db/changelog-master.yaml

  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    properties.hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true

logging:
  file.name: log/sql.log
  level:
    org.hibernate:
      SQL: debug
      type.descriptor.sql.BasicBinder: trace
    org.springframework: error
